name: dummy-servers

services:
  # Client used for testing
  client:
    hostname: devserver
    build:
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "2222:22"
    volumes:
      - ./docker/persistent/mnt:/mnt/
      - ./scripts:/root/scripts/
      - ./docker/persistent/home:/home/
    networks:
      - secured
      - exposed
    depends_on:
      - server1
      - server2
      - server3
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4"
    #       memory: "4g"

  # Servers used for testing
  server1:
    hostname: server1.internal
    build:
      dockerfile: ./docker/Dockerfile.server
    networks:
      - secured
  server2:
    hostname: server2.internal
    build:
      dockerfile: ./docker/Dockerfile.server
    networks:
      - secured
  server3:
    hostname: server3.internal
    build:
      dockerfile: ./docker/Dockerfile.server
    networks:
      - secured

networks:
  secured:
  exposed: