name: dummy-servers

services:
  # Client used for testing
  client:
    hostname: devserver
    build:
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "2222:22"
    volumes:
      - ./docker/persistent/mnt:/mnt/:rw
      - ./scripts:/root/scripts/:ro
      # - ./docker/persistent/home:/home/
    networks:
      - secured
      - exposed
    depends_on:
      - server1
      - server2
      - server3
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4"
    #       memory: "4g"

  # Servers used for testing
  server1:
    hostname: server1.internal
    build:
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ./docker/persistent/mnt:/mnt/:rw
    networks:
      - secured
  server2:
    hostname: server2.internal
    build:
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ./docker/persistent/mnt:/mnt/:rw
    networks:
      - secured
  server3:
    hostname: server3.internal
    build:
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ./docker/persistent/mnt:/mnt/:rw
    networks:
      - secured
  # php-apache:
  #   build:
  #     context: ./src/example-app/
  #     dockerfile: Dockerfile
  #   ports:
  #     # - 8080:80
  #     - 8080:6543
  #   networks:
  #     - secured
  #     - exposed


  # MySQL and PHPMyAdmin for testing
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - secured
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      # PMA_USER: root
      # PMA_PASSWORD: root
      PMA_SAVEDIR: /mnt/phpmyadmin/
    attach: false
    depends_on:
      - mysql
    ports:
      - "8090:80"
    volumes:
      - ./docker/persistent/mnt:/mnt/:rw
    networks:
      - secured
      - exposed

  # ===================> CISCO IOS Switches <===================
  # These are fake switches, not real Cisco IOS images :D
  switch1:
    image: internap/fake-switches
    environment:
      - SWITCH_MODEL=cisco_2960_48TT_L
    hostname: switch1.internal
    ports:
      - "2201:22"
    networks:
      - secured
  switch2:
    image: internap/fake-switches
    environment:
      - SWITCH_MODEL=cisco_2960_24TT_L
    hostname: switch2.internal
    ports:
      - "2202:22"
    networks:
      - secured

networks:
  secured:
  exposed:

volumes:
  mysql:
    driver: local